src/main/java/io/lbry/lbrynet/Utils.java
src/main/python/lbrynetservice.py

- Added KeyStore handling and encryption / decryption methods to the `Utils` Java class.
- Enabled daemon server RPC authentication in service startup.
- Patched the `load_api_keys`, `save_api_keys` and `initialize_api_key_file` methods in `lbrynet.daemon.auth.util` to handle encrypted API key loading / saving using the Android KeyStore.

Daemon RPC authentication with encrypted api key storage

---

app/src/component/fileList/index.js
app/src/component/fileList/view.js
app/src/page/channel/index.js
app/src/page/channel/view.js
app/src/styles/channelPage.js

This the first step of the channel page implementation. The plan is to create a future PR to handle:
- fetching claims from subsequent pages and displaying them using infinite scroll until the last page has been reached
- sorting claims
Most of the `fileList` component is taken from https://github.com/lbryio/lbry-app/tree/master/src/renderer/component/fileList

Implement channel page with just the first page of results

---

DOCKER-DEV.md
scripts/docker-setup.sh
scripts/lbry-android.sh

Needs pinned dependency: "rn-fetch-blob": "0.10.15"
Otherwise you will get:
```
error: package androidx.core.content does not exist
```

DOCKER-DEV: Add arm64 glibc headers from #606 and other refactors

---

Dockerfile

Fixes #831
Issue Number: 831
Cannot create container
Container is created as expected
https://github.com/npm/cli/issues/681

Fix npm install

---

app/src/main/res/values/strings.xml

Fixes minor spelling typo.
Since it's just a typo for this specific case (no change in ID or sentence structure), it wouldn't matter much to the translators.
For future reference:  What I'm not sure if how this will get propagated to the translators.  If a change is made in this file, will it get published to them nightly?  Will major changes be automatically marked as "require re-translation"?

Fix minor typo for string in 'generate_address_hint'.

---

app/src/main/java/io/lbry/browser/adapter/CommentListAdapter.java
app/src/main/java/io/lbry/browser/model/Comment.java
app/src/main/java/io/lbry/browser/tasks/CommentListHandler.java
app/src/main/java/io/lbry/browser/tasks/CommentListTask.java
app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java
app/src/main/java/io/lbry/browser/utils/Lbry.java
app/src/main/res/layout/fragment_file_view.xml
app/src/main/res/layout/list_item_comment.xml
app/src/main/res/values/strings.xml

- [] I have checked that this PR does not introduce a breaking change
Issue Number: resolves #652 
No comments or commenting under video
You can now read the first "page" of comments on a video
There is still a lot of commenting features that aren't done yet like "infinite scroll". For now it just loads as many comments as possible on the first page. There is also lacking of the ability write comments, read replies, write replies, click on usernames to go to their channel, and and see the poster's icon. So I don't know if this should close the referenced issue but I'd imagine it'd be better to separate these "different" features into separate issues.
I'm not sure if this is a "breaking change" …

Added ability to read comments on claims

---

build.gradle

LBRY SDK is now hosted on JCenter, which is already available out-of-the-box on Android Studio. The Bintray url is no longer reguired. When building LBRY on F-Droid, I have to remove this line on the build YAML script and it is building correctly.
On my local machine, Android Studio directly builds the app after removing it.
Issue Number:
Use certain library repository
Don't use it as the required one is already integrated into the toolchain.

Bintray repository is no longer needed

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/lbry/browser/utils/LbryUri.java

PR Checklist
Issue Number: #957 
LBRY Android is not offered when user clicks on open.lbry.com links.
LBRY Android will show on lists of apps which can manage open.lbry.com links
It adds itself for intents with an '`https://`" protocol schema and an '`open.lbry.com`' host on AndroidManifest.
When system observes an intent from user to visit any link of the form `https://open.lbry.com:`, it will show a dialog with a list of all apps registered for that intent. When user selects LBRY app, the system will open it and it will recieve the link, which this PR will transform into something like an lbry:// intent, instead of managing it separatelly.
It modifies regex parts as following:
* Add 'https' as …

Add open.lbry.com deep-links

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/lbry/browser/MainActivity.java

Issue Number: 660
LBRY Android is not shown on Send To list of apps
LBRY Android will be shown when user wanted to share (=send) a video/image/text file. Then user could publish the file as if it had selected the file from the file picker.
Sorry for previous cancelled PR. I had to sync the branch with master one. This PR is not intended to do the same for files stored "on the cloud", although it could also improve the experience for those users.

Allow to publish files via Send To feature

---

app/src/main/java/io/lbry/browser/MainActivity.java
app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/settings.xml

Issue Number:
Buffering events are sent to LBRY without user permission. User cannot disable this behavior. This makes Tracking AntiFeature to appear in FDroid store listing.
No buffering event is sent to LBRY servers by default. User can enable this events to be sent at will. FDroid will not show the Tracking AntiFeature as user is in control of data being sent and the default is to not send it.
This is a change required to remove the Tracking AntiFeature from FDroid listing. This PR adds the Preference to upstream lbry-android with a default 'true' value. Then FDroid build script will change default to 'false' so no data is sent by default on the APK built by FDroid.
Translation on 1 new string …

Add setting to enable sending buffering events

---

app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java
app/src/main/res/drawable-anydpi/ic_unpublish.xml
app/src/main/res/layout/fragment_file_view.xml
app/src/main/res/values/strings.xml

Issue Number: #987 
Inability to download your own videos.
The ability to download new videos. Due to the old reuse of the delete action for both deleting from files and unpublishing, a distinction had to be made if both were to be possible. So, I put an unpublish button in the description (since it wouldn't fit in the current actions area) and removed the ability to unpublish from the old delete button.

Add ability to download & delete your own videos and move unpublish button to description

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/lbry/browser/utils/LbryUri.java
app/src/test/java/io/lbry/browser/utils/LbryUriTest.java

…sts for LbryUri parse() method
Issue Number:
LBRY.TV and other links are not captured by LBRY Android when clicked on other apps
LBRY Android will be offered to users when they click on any LBRY.[TV|LAT|IN|FR] hosted link.
Furthermore, I have also added unit tests for the LbryUri.parse(String, bool) method. In order to run them, it could be required to edit the 'Shorten command line' configuration and change the value to 'JAR Manifest', which was the one I used to run them.

Support some lbry hosts to deep links. Add unit tests

---

app/src/main/res/layout/fragment_publish_form.xml

Increased size of currency selection spinner in publish form fragment
Now spinner is in proper size to display "LBRY Credits" default value
Layout issue in publishing form fragment - currency selection spinner 
inside Price section (when Price is toggled on)
now big enough to display default currency "LBRY Credits"
(Increased spinner width)
Issue Number: 1025
Currency selection spinner shows truncated string "LBRY .."
instead of the full default value "LBRY Credits"
Currency selection spinner now displaying the full "LBRY Credits" value

Fix issue #1025

---

app/src/main/java/io/lbry/browser/MainActivity.java

Dismiss all active dialog fragment when entering PiP mode
So that PiP window contain the video only
Issue Number: 1030
Support/Repost dialogs interfere with video displayed in PiP mode
When entering PiP mode - any unfinished dialogs are dismissed, 
leaving the PiP clean of any unrelated artifacts

Fix issue #1030

---

app/src/main/java/io/lbry/browser/MainActivity.java

Hide notifications when entering PiP mode
Issue Number: 1034
Notifications container remain visible when entering PiP mode , blocking video
Video visible
Notifications get hidden when entering PiP mode

Fix issue #1034

---

app/src/main/res/layout/list_item_transaction.xml

Replaced gravity pinning to "end" instead of "right"
Pinned claim id which could be in rtl and ltr scripts to the start of the layout
Issue Number: 1038
Claim ID misaligned with transaction description in Recent Transaction/T. History
Claim ID aligned with transaction description

fix issue 1038

---

app/src/main/res/layout/list_item_transaction.xml

Transaction amount text Direction changed to LTR.
Transaction amount pinned to end of view
Issue Number: 1040
RTL layouts displaying negative transaction amounts with misplaced sign as (amount)(minus)
RTL layouts displaying negative transaction amounts as (minus)(amount)
Stable - not modifed
Fixed
(Ignore separate RTL UI issues - further fixes in other PR's)
Pure numeric texts should always be LTR text direction

fix issue 1040

---

app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java

Issue Number: #960 (partial fix, do not close it)
Due to some change introduced in Chrome, WebViews are unable to render anything after the first '#'. If that happens at the beginning of the markdown document, the HTML render will not be displayed, although the HTML code itself is correct.
Strings like '#1', '#hashtag' will make the problem appear.
This fix changes the '#' into '%23' on the HTML generated code from markdown.
The issue indicated above was about two distincts problems. This one fixes the one from the German blog post. That file was modified, so it is no longer showing the problem. However, it was identified as being related to '#'.
The other one was about lbrycast style of claims, …

Fix for text not rendering after # in markdown

---

app/src/main/res/layout/floating_wallet_balance.xml

Floating wallet balance/rewards now visible in RTL layout
Issue Number: #1043 
Floating wallet fragment pinned to the bottom right of the screen (regardless of layout direction)
Floating wallet fragment does not display wallet balance on RTL layout
Floating wallet fragment pinned to the bottom end of the screen - generalized LTR/RTL solution
Floating wallet fragment now displays both rewards and balance
Not modified
Fixed
I swear I'm not splitting every little RTL issue to separate PR's
I'm genuinely finding them one at a time 🤷

Fix floating wallet/rewards bar for RTL layout

---

app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java
app/src/main/res/layout/fragment_file_view.xml
app/src/main/res/values/strings.xml

Issue Number: #419 
If LBRY doesn't include the capacity of showing the content on the claim, user should download file and search for it on its device and then open it
User is shown a notice about LBRY inability to show content and a button which allows it to choose a compatible app when clicked.
This PR adds a new string and reuses other one.
In order to test it, reviewer could search for "PDF" on LBRY Android and look for one without a time on the snapshot. I used the ones with "UOC" on their title. "UOC PDF" could be a better approach for the search text.

Offer opening unsupported filetypes with external app

---

app/src/main/java/io/lbry/browser/model/Comment.java
app/src/main/java/io/lbry/browser/tasks/CommentListTask.java

Issue  Number: #948 
Replies to comments are ordered in a way which newest ones appear first, making difficult to follow the conversation if there are lots of replies, as it requires to scroll down to the latest one and then scrolling up while reading adn then scrolling down again to read next comment.
Replies are ordered on its chronological order: older are shown first and followed by newer ones.
New behavior is also consistent with LBRY.TV and ODYSEE.COM. See for example https://lbry.tv/microsoft:2. Replies from the comments are the bottom are now shown in the same order in both the site and LBRY Android app.

Sort replies from oldest to newest

---

app/build.gradle
app/src/main/java/io/lbry/browser/utils/Helper.java

Issue Number: https://github.com/lbryio/lbry-fdroid/issues/6
Helper imports a whole class from Google Messaging Service just to do some string transformation. That import injects some artifacts from Play Services which cannot be used on FDroid build, although they are required on the regular LBRY Play Store release
Using the encodeHex method from Apache Commons artifact it is possible to exclude those Play Services injected dependencies without breaking the code.
New behavior of SHA256() method HAS NOT BEEN tested.

Replace Hex class from GMS with the one from Apache

---

app/src/main/java/io/lbry/browser/model/Comment.java
app/src/main/java/io/lbry/browser/tasks/CommentCreateTask.java
app/src/main/java/io/lbry/browser/ui/channel/ChannelCommentsFragment.java
app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java
app/src/main/res/layout/container_comment_form.xml
app/src/main/res/layout/fragment_file_view.xml
app/src/main/res/values/strings.xml

Issue Number: #1042 
Comments requires a 1 LBC top to be paid
Commenting does not require any tip to be paid
Not sure if warning that comment will be posted should be removed entirely or not. Will remove if asked.

Removed comment tips

---

app/src/main/java/io/lbry/browser/ui/wallet/WalletFragment.java

Issue Number: #1086
Wallet send notification only shows 2 decimals (if present) even though 4 decimal sends are allowed.
Wallet send notification now shows 4 decimals (if present).

Changed wallet send notification to accept 4 digit decimal

---

app/src/main/java/io/lbry/browser/MainActivity.java
app/src/main/res/layout/app_bar_main.xml

On some cases it could happen that the list which shows startup stage errors is also showing a scroll bar, which also makes not all stages be seen at the same time
Listview is measured and resized to a height which would allow all stages statuses to be seen at the same time
Testing on the emulators didn't show the current behavior. However, testing on my physical device did show it. I suggest testing this PR on a physical device.
ListView layout_height on app_bar_main.xml was changed to "0dp" as Android Studio was recommending that change.

Avoid showing vertical scroll bar on stage error listview

---

app/build.gradle
app/src/androidTest/java/io/lbry/browser/utils/HelperTest.java
app/src/main/java/io/lbry/browser/utils/Helper.java

On devices running older than Android Pie, an exception will be raised when using Helper.SHA256 method.
Now code has been splitted so newer versions will run curent code, while older ones will run the patched one.
An instrumented test has been added. I was unable to test it on an emulator. Running the test on my physical Android 8.1 (Oreo MR1) device, it is now working as expected.
To run the instrumented test, open the "tests" view on the Project sidebar tab, an click the "Run" icon on the HelperTest.java on the androidTest folder.

Fix NoSuchMethod exception for HelperSHA256 on API Level prior to P

---

app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java

Issue Number: #960 -still partially fixed, don't close it-
Some problems are still showing up when using the octothorpe character
New code fixes it by encoding the HTML string using Base64, as recommended by [Google](https://developer.android.com/reference/android/webkit/WebView#loadData(java.lang.String,%20java.lang.String,%20java.lang.String)). Additionally, it no longer requires to run a regex matching, making it faster.
Search for "octothorpe-test" on the LBRY Android app and open the one on the "javirid" channel, as it includes some problematic cases. Currently it shows a few problems still. With this PR applied, everything looks fine. Compare it with the rendered Markdown on …

Use Base64 to encode html when rendering Markdown files

---

app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml

Issue Number: #960 -partial fix, don't close-
`<code>` tag is not rendered like on LBRY Desktop or alternative websites
`<code>` tag is now rendered like in the desktop app, both in light and dark theme.
CommonMark offers the possibility of adding attributes to a node. I think this is the way it should be done, instead of embedding the CSS. This way, style is only added when needed. Code to add the style to every tag is only run when required.

Styling <code> tag for Markdown content

---

app/src/test/java/io/lbry/browser/utils/LbryUriTest.java

Issue Number:
LbryUri.toTvString() lacks its unit test
Now it ill be possible to test for method to do what it is supposed to do
This is related to #1126, but it is not a fix for it. Providing a fix would then not need to run the app on an emulator, as it will only be needed to run the test, which can be done just with the Java Virtual Machine.

Add unit test for LbryUri.toTvString

---

app/src/main/java/io/lbry/browser/tasks/CommentCreateTask.java
app/src/main/java/io/lbry/browser/tasks/CommentListTask.java
app/src/main/java/io/lbry/browser/utils/Comments.java

Issue Number: #1131 
Any action related to comments is performed through SDK
App uses SDK only to sign parameters with the channel private key. Everything is performed by making requests directly to Comment Server -aka Commentron-.
Currently app is lacking the capability of removing or editing comments. That features has not been added on this PR.
A new `Comments` class has been added on the utils package; it will act as a 'Helper'.
From the issue description, it seems that the user could change the server it wanted to use for commenting, so a generic performRequest() is included, but it is currently been called with the default server as a parameter.

Use commentron instead of Comment SDK calls

---

app/src/main/java/io/lbry/browser/MainActivity.java
app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/settings.xml

Issue Number: #844 
Video and audio content plays automatically when shown on the detail view
By default, content will still play when opened, but user will be able to disable the autoplay of media.
This PR changes some methods which have been deprecated for ExoPlayer2 API.
A new string has been added for the setting string which is shown on Settings fragment. Translation will be needed. String was copied from LBRY.TV
I have been testing it this way:
1. Open a file which hasn't been viewed yet and let it play for some time
2. Open another file from the Related content list which wasn't opened yet
3. Open a file which had already been consumed, preferably a different one from the ones used on …

Allow media to be played automatically

---

app/src/main/java/io/lbry/browser/ui/channel/ChannelCommentsFragment.java
app/src/main/java/io/lbry/browser/ui/channel/ChannelFragment.java
app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java
app/src/main/res/layout/fragment_channel_comments.xml
app/src/main/res/layout/fragment_file_view.xml
app/src/main/res/values/strings.xml

Issue Number:1146
See #1146
See #1146 
In comment fragment for channel, the comment form visibility is GONE to avoid it been shown just before being replaced by the texto for channels having comments disabled. This change is not needed for FileViewFragment as this replacement occurs while not in user view.
Two new strings have been added. Text was taken from LBRY.TV. Translation will be needed.
This commit adds code to code which is already been duplicated in various files. This will be fixed in an upcoming PR which replaces comment form with a new widget instead of a layout which should be <included>

Hide support button and comments consistently with claim tags

---

app/src/main/java/io/lbry/browser/MainActivity.java
app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java

Issue Number: partially #1054 (DON'T CLOSE)
Latest comment or text cannot be read at the bottom of the fragment which shows the content (FileViewFragment)
Floating balance container will be animated to disappear to the bottom of the screen when user has scroll to the bottom of the screen. When there are no comments and last item is the comment form, the balance will not be animated, as there is enough room to see and interact with the form.
When user scrolls some distance in the upward direction, balance container will be animated again into the screen.
The same fix can be applied to channel screen. This will come in another PR, as it requires more time because of the way tabs work in Android

Move the wallet floating button away when scroll gets to the bottom

---

app/src/main/java/io/lbry/browser/utils/LbryUri.java

Issue Number: #1126 
Unit test for toTvString() fails
Unit test for toTvString() no longer fails. This is the method used for getting a sharing link, so when the unit test succeeds, the sharing link should be ok

Use ':' as separator for LBRY.TV sharing links

---

app/src/main/java/io/lbry/browser/VerificationActivity.java
app/src/main/java/io/lbry/browser/ui/verification/ManualVerificationFragment.java
app/src/main/res/layout/fragment_verification_manual.xml
app/src/main/res/values/strings.xml

Show the Close button after phone number has been verified
Issue Number: #1085 
No way to verify account other than Twitter, Discord chat or paying fee
Now it is also possible to be verified using the user mobile phone number
This PR adds some strings which should be translated.
Adds a button to the manual verification fragment. When user clicks on it, a new fragment shows, asking user to introduce its phone number. Then a SMS is send to it, which user should introduce inte the fragment. If it matches, the fragment closes. Until #1167 is fixed, the next fragment shown to user is the verification fragment again.
This PR also re-activates the onBackPressed() callback, to allow user to go back when …

Enable phone verification

---

app/src/main/java/io/lbry/browser/ui/wallet/WalletFragment.java
app/src/main/res/layout/card_wallet_balance.xml

This fix uses two services:
- The geolocation API service from LBRY for filtering users not on North-America
- IP-API.com service when the LBRY service returns user is in North-America
This way users not on North-America won't see their IPs sent to a third-party provider.
Issue Number: #1179 
For IPs on the US, users are shown a message about using Bittrex to exchange LBRY Credits to USD. Bittrex is no longer allowing that for users in the US, but LBRY Android users are going to see the message
Message is not being shown
By default, the message is not shown. Then, depending on the IP of the user, it is programmatically made visible. Network requests are using Java Future, because AsyncTask is now …

Don't show link to Bittrex

---

app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java

Issue Number: #1189 
App crashes when user tries to consume anonymous content -and potentially content without tags-
A check has been introduced to avoid the crash and show the content

Fix crash for anonymous content or without tags

---

app/src/main/java/io/lbry/browser/utils/LbryUri.java
app/src/test/java/io/lbry/browser/utils/LbryUriTest.java

Issue Number: #1053 
It replaces colon with octoshape character
Accepts both colon and octoshape as modifiers for claimIDs while changing accepted sequence number modifier to an asterisk as noted on spec.lbry.com URL section

Accept colon or octoshape as claimID modifier character
