lbryio/lbry-android

- buildozer.spec.sample
- buildozer.spec.travis
- p4a/pythonforandroid/build.py
- p4a/pythonforandroid/patching.py
- p4a/pythonforandroid/recipe.py
- p4a/pythonforandroid/toolchain.py
- Minimum Android API support.
- Minimum Android API set to 21.
> Integrate fixes from https://github.com/kivy/python-for-android/pull/1197

- BUILD.md
Added a missing dependency listed on docs
> Update dependencies needed on docs.

- app/src/component/AppNavigator.js
- app/src/component/searchRightHeaderIcon/index.js
- app/src/component/searchRightHeaderIcon/view.js
Added a new component as I needed to hookup redux to clear the search results and navigate back, this PR will solve #113 I think.
> Clear search results when clearing search results as reported on issue #113

- .gitignore
- Vagrantfile
- buildozer.spec.vagrant
Please don't merge yet, still working on it, made this PR for visibility. 😄 
I'll update the description when it's ready.
Thanks!
> Add Vagrantfile for easier development environments

- .travis.yml
- Vagrantfile
- app/package-lock.json
- app/package.json
- buildozer.spec.sample
- buildozer.spec.travis
- buildozer.spec.vagrant
- p4a/pythonforandroid/bootstraps/lbry/build/templates/build.tmpl.gradle
- p4a/pythonforandroid/bootstraps/lbry/build/templates/settings.tmpl.gradle
Depends on https://github.com/lbryio/react-native-video/commit/d8bc0bf0192814ff98f07882d5f03aee5d5d89a9
> Build and package modifications for react-native-video module updates

- app/package-lock.json
- app/src/component/uriBar/index.js
@akinwale I didn't test this but that should be all you need. 
For https://github.com/lbryio/lbry-redux/pull/67
> use new search suggestion selector

- app/src/component/floatingWalletBalance/view.js
- app/src/component/mediaPlayer/view.js
- app/src/page/file/view.js
- app/src/styles/mediaPlayer.js
Also implemented a couple of minor fixes
* added activity indicator for floating wallet balance
* fix error with playerBackground as detailed in https://github.com/lbryio/lbry-android/issues/258
> implement touch to seek for media playback using the seek bar

- .github/issue_template.md
- README.md
now LBRY have a new website called lbry.com
> change io to com

- app/src/component/fileListItem/view.js
- app/src/component/progressBar/index.js
- app/src/component/progressBar/view.js
- app/src/page/splash/view.js
- app/src/styles/fileList.js
Replaces use of the platform-dependent `ProgressBarAndroid` component.
> create progress bar component

- app/src/component/AppNavigator.js
- app/src/component/drawerContent/index.js
- app/src/component/drawerContent/view.js
- app/src/page/transactionHistory/view.js
- app/src/styles/discover.js
> add custom drawer content to navigate to the topmost item in nested stacks

- DOCKER.md
After much trial and error, building the app via Docker is successful. This is my story.
> Added updated Docker instructions

- .dockerignore
- .gitignore
- DOCKER-DEV.md
- Dockerfile
- scripts/docker-build.sh
- scripts/docker-setup.sh
- scripts/lbry-android.sh
This encapsulates all the docker commands into a single bash CLI script for a local development environment.
This successfully builds the apk and provides instructions for connecting a real android device via adb for testing with hot-reload.
README: https://github.com/EnigmaCurry/lbry-android/blob/docker-build/DOCKER-DEV.md
> DOCKER-DEV: Local development in a docker container

- QUICKSTART.md
Signed-off-by: Akshit Sarin <akshitsarin99@gmail.com>
'*toolcahin* to toolchain'
> Fixed a typo in QUICKSTART.md

- README.md
Updated the file with the screenshots of the most recent version of the app. The existing screenshot had been of a previous version .
> Updated screenshots

- .github/PULL_REQUEST_TEMPLATE.md
Now contributors of this repo can send PRs with a standardised description template. Every GitHub repo should have a PR template as it eases the procedure for both contributors and code reviewers.
With this checklist reviewers can make sure how many guidelines have been followed and prioritise their PR reviews as the number of checked items appear on the PR page.
------------------
> Initialised a GitHub PR Template

- BUILD.md
Updates the google-services.json path as per the current directory structure
Fixes lbryio/lbry-android#722
> Update google-services.json path in BUILD.md #722

- p4a/pythonforandroid/bdistapk.py
- p4a/pythonforandroid/bootstraps/common/build/build.py
- p4a/pythonforandroid/bootstraps/lbry/build/build.py
- p4a/pythonforandroid/graph.py
- p4a/pythonforandroid/recipes/android/src/android/mixer.py
- p4a/pythonforandroid/toolchain.py
- recipes/android/src/android/mixer.py
sorted function has been replaced with sort function wherever possible. It is faster and more readable than sorted function.
min function has been used instead of sorting and then picking the first element. Again, it will be faster and more readable.
> Perf: Use of sort and sorted functions optimized

- app/src/main/java/io/lbry/browser/utils/Predefined.java
- app/src/main/res/values-ca/strings.xml
- app/src/main/res/values/strings.xml
Issue Number:
Catalan language is complete on Transifex. This PR adds it to the list of available languages.
> Add Catalan language

- app/src/test/java/io/lbry/browser/utils/HelperTest.java
Issue Number:
No way to ensure changes in SHA256 method result in the same output.
Running this unit test after performing any modification to SHA256 method will allow developers and reviewers detect if the code change still returns the same result.
This PR should be merged before https://github.com/lbryio/lbry-android/pull/1067 to ensure the output is still the same. Reviewer will be able then to see test works before merging PR 1067 so it could verify changes in that PR return the same hash.
> Add unit test for Helper.SHA256(String)

- README.md
Developer should research a way to skip error when syncing project
Instructions on how to skip the error for Twitter are provided on the README file
> Provide instructions to add dummy Twitter API credentials

- app/src/main/java/io/lbry/browser/MainActivity.java
- app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java
- app/src/main/res/layout/activity_verification.xml
- app/src/main/res/layout/app_bar_main.xml
- app/src/main/res/layout/container_comment_form.xml
- app/src/main/res/layout/content_main.xml
- app/src/main/res/layout/dialog_content_from.xml
- app/src/main/res/layout/dialog_content_scope.xml
- app/src/main/res/layout/dialog_content_sort.xml
- app/src/main/res/layout/exo_playback_control_view.xml
- app/src/main/res/layout/fragment_all_content.xml
- app/src/main/res/layout/fragment_channel.xml
- app/src/main/res/layout/fragment_channel_content.xml
- app/src/main/res/layout/fragment_channel_form.xml
- app/src/main/res/layout/fragment_file_view.xml
- app/src/main/res/layout/fragment_following.xml
- app/src/main/res/layout/fragment_gallery.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/fragment_publish.xml
- app/src/main/res/layout/fragment_publish_form.xml
- app/src/main/res/layout/fragment_shuffle.xml
- app/src/main/res/layout/list_item_channel.xml
- app/src/main/res/layout/list_item_featured_search_result.xml
- app/src/main/res/layout/list_item_notification.xml
- app/src/main/res/layout/list_item_reward.xml
- app/src/main/res/layout/list_item_startupstage.xml
- app/src/main/res/layout/list_item_stream.xml
- app/src/main/res/layout/list_item_tag.xml
> Some fixes for lint

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java
- app/src/main/java/io/lbry/browser/ui/findcontent/ShuffleFragment.java
- app/src/main/java/io/lbry/browser/utils/ExoplayerAudioRenderer.java
Upgrading ExoPlayer in preparation of backround playback.
> Upgrade ExoPlayer from 2.11.4 to 2.12.2

- app/src/androidTest/java/io/lbry/browser/utils/HelperTest.java
- app/src/main/java/io/lbry/browser/utils/Helper.java
- app/src/test/java/io/lbry/browser/utils/HelperTest.java
Helper.SHA256(String) method is now unused.
Method is no longer available as it is no longer needed.
> Remove Helper.SHA256() method

- app/src/main/java/io/lbry/browser/tasks/wallet/UnlockTipsTask.java
> Fix mass tips unlocking

- app/src/main/java/io/lbry/browser/utils/LbryUri.java
- app/src/test/java/io/lbry/browser/utils/LbryUriTest.java
> Decode and encode urls with non-authorized characters

- app/src/main/java/io/lbry/browser/ui/channel/ChannelFragment.java
Issue Number: #1054 
Floating wallet will disappear on About and Comment tabs on the Channel fragment
> Hide floating wallet on the Channel fragment

- app/src/main/java/io/lbry/browser/MainActivity.java
- app/src/main/java/io/lbry/browser/tasks/lbryinc/NotificationListTask.java
- app/src/main/java/io/lbry/browser/ui/BaseFragment.java
Issue Number: #1142 DON'T CLOSE
> Notification improvements

- app/src/main/java/io/lbry/browser/ui/findcontent/FileViewFragment.java
Issue Number: #1095 
Explicitly downloaded files are saved to private storage folder
After downloading the file, it will be copied to the generic Donwload or Movies or Images folders depending its mime-type
Downloaded file will still be on private app-scope storage. It won't be moved to the new folder
> Copy file to public Downloads directory

- app/src/main/java/io/lbry/browser/ui/wallet/WalletFragment.java
> Show total wallet balance in USD instead of spendable balance conversion

- app/src/main/java/io/lbry/browser/utils/Lbry.java
Issue Number: https://github.com/lbryio/lbry-android/issues/1243
Fails to fetch any content via the old api.lbry.tv URL.
Content is now resolving via the new Odysee backend URL
> Update LBRY_TV_CONNECTION_STRING to new Odysee Backend
